### ISSUE TITLE
File name become the url path

### ISSUE THREAD

**Issue by airtonzanon** [augustohp/ship#2] opened 2019-09-04 21:09 UTC
When I'm installing the script with sinister, the name becomes `fjhO5`

Example:
```
$ sh <(curl -sSL http://git.io/sinister) --local --chmod 755 --url https://git.io/fjhO5
fjhO5 was installed successfully
```

I saw that sinister has the parameter `--name`, but it didn't work well.

So just used `mv`
```
sh <(curl -sSL http://git.io/sinister) --local --chmod 755 --url https://git.io/fjhO5 && mv ~/bin/fjhO5 ~/bin/ship
```

But it will not be sustainable hehe.

**Comment by augustohp** [comment] 2019-09-05 05:56
Thanks a lot for testing and creating the bug! I am terribly sorry that I didn't test that workflow before writing it on the README. There is an [upstream problem][1] I am waiting to be fixed, if it doesn't get merged by the end of the week I will fork and start using my fork for installation.

[1]: https://github.com/jamesqo/sinister/pull/5

**Comment by augustohp** [comment] 2019-09-05 06:12
🛠 Installation instructions should be **fixed now**. I will close this issue if *upstream* gets merged or 1 week passes from now. 😉 

Thanks again for reporting. Let me know if you miss anything or if it was useful.

**Comment by augustohp** [comment] 2019-09-23 14:28
I am closing this, there is the possibility that `upstream` _merge_ will take a little while (or never happen). Thank you for reporting! 🙇 

I would note that, although not solved in the `upstream`, the issue is resolved in this repository.

**Closed as completed by augustohp** 2019-09-23 14:28 UTC
Labels: bug
